CREATE TABLE COCHE_TIPO (
    ID                          VARCHAR(50)    PRIMARY KEY,
    NOMBRE                      VARCHAR(50)    NOT NULL,
    PRECIO_BASE                 NUMERIC(10,2)  NOT NULL DEFAULT 0 CHECK (PRECIO_BASE >= 0),
    PUNTOS_LEALTAD              INT            NOT NULL DEFAULT 0 CHECK (PUNTOS_LEALTAD >= 0)
);

INSERT INTO COCHE_TIPO  (ID,            NOMBRE,         PRECIO_BASE,    PUNTOS_LEALTAD)
VALUES
                        ('PREMIUM',     'Premium',      300.00,         5),
                        ('SUV',         'SUV',          150.00,         3),
                        ('SMALL',       'Small',        50.00,          1);

CREATE TABLE COCHE (
    ID                          NUMERIC(16,0)  PRIMARY KEY,
    MATRICULA                   VARCHAR(20)    NOT NULL UNIQUE,
    COCHE_TIPO_ID               VARCHAR(50)    NOT NULL REFERENCES COCHE_TIPO(ID)
);

CREATE SEQUENCE SEQ_COCHE
     START WITH 1
     INCREMENT BY 1
     MAXVALUE 9999999999999999
     MINVALUE 1
     NOCYCLE
     CACHE 20;

CREATE TABLE CLIENTE (
    ID                          NUMERIC(16,0)  PRIMARY KEY,
    NIF                         VARCHAR(9)     UNIQUE,
    NOMBRE_COMPLETO             VARCHAR(120)   NOT NULL,
    EMAIL                       VARCHAR(120)   NOT NULL,
    TOTAL_PUNTOS_LEALTAD        NUMERIC(16,0)  NOT NULL DEFAULT 0 CHECK (TOTAL_PUNTOS_LEALTAD >= 0)
);

CREATE SEQUENCE SEQ_CLIENTE
     START WITH 1
     INCREMENT BY 1
     MAXVALUE 9999999999999999
     MINVALUE 1
     NOCYCLE
     CACHE 20;

CREATE TABLE ALQUILER (
    ID                          NUMERIC(16,0)  PRIMARY KEY,
    CLIENTE_ID                  NUMERIC(16,0)  NOT NULL REFERENCES CLIENTE(ID),
    FECHA_INICIO                TIMESTAMP      NOT NULL,
    FECHA_FIN                   TIMESTAMP      NOT NULL CHECK (FECHA_FIN >= FECHA_INICIO),
    TOTAL_BASE                  NUMERIC(12,2)  NOT NULL DEFAULT 0 CHECK (TOTAL_BASE >= 0),
    TOTAL_RECARGO               NUMERIC(12,2)  NOT NULL DEFAULT 0 CHECK (TOTAL_RECARGO >= 0),
    TOTAL_ALQUILER              NUMERIC(12,2)  NOT NULL DEFAULT 0 CHECK (TOTAL_ALQUILER >= 0),
    PUNTOS_LEALTAD              INT            NOT NULL DEFAULT 0 CHECK (PUNTOS_LEALTAD >= 0)
);

CREATE SEQUENCE SEQ_ALQUILER
     START WITH 1
     INCREMENT BY 1
     MAXVALUE 9999999999999999
     MINVALUE 1
     NOCYCLE
     CACHE 20;

CREATE TABLE ALQUILER_COCHE (
    ID                          NUMERIC(16,0)  PRIMARY KEY,
    ALQUILER_ID                 NUMERIC(16,0)  NOT NULL REFERENCES ALQUILER(ID),
    COCHE_ID                    NUMERIC(16,0)  NOT NULL REFERENCES COCHE(ID),
    COCHE_TIPO_SNAPSHOT         VARCHAR(50)    NOT NULL,
    DIAS_BASE                   INT            NOT NULL CHECK (DIAS_BASE > 0),
    PRECIO_BASE                 NUMERIC(12,2)  NOT NULL CHECK (PRECIO_BASE >= 0),
    DIAS_EXTRA                  INT            NOT NULL DEFAULT 0 CHECK (DIAS_EXTRA >= 0),
    PRECIO_EXTRA                NUMERIC(12,2)  NOT NULL DEFAULT 0 CHECK (PRECIO_EXTRA >= 0),
    TOTAL_COCHE                 NUMERIC(12,2)  NOT NULL DEFAULT 0 CHECK (TOTAL_COCHE >= 0),
    FECHA_DEVOLUCION            TIMESTAMP,
    UNIQUE (ALQUILER_ID, COCHE_ID)
);

CREATE SEQUENCE SEQ_ALQUILER_COCHE
     START WITH 1
     INCREMENT BY 1
     MAXVALUE 9999999999999999
     MINVALUE 1
     NOCYCLE
     CACHE 20;